FROM node:18-alpine
WORKDIR /opt/app
ADD package.json package.json
RUN npm install --legacy-peer-deps && echo "Dependencies installed"
ADD . .
ENV NODE_ENV=production
RUN npm run build
CMD ["node_modules/.bin/next", "start"]
EXPOSE 3000